-- PostgreSQL init -- generated by deploy.sh on Mon Aug 31 13:06:49 PDT 2026
-- Do not edit manually; re-run deploy.sh to regenerate.
-- Note: this file only takes effect when the postgres-data volume is empty.

-- =======================================================
-- Per-service roles (users)
-- =======================================================
CREATE USER litellm   WITH PASSWORD 'R4op8ebfpzRS2X93SKSu';
CREATE USER flowise   WITH PASSWORD 'fcdzeTd8k8GAASZqlFNZ';
CREATE USER langfuse  WITH PASSWORD 'Gb5iEuDRM4hOQz502QDw';
CREATE USER agentuser WITH PASSWORD 'wLsx5AxhuBxdbXKRQv4L';

-- =======================================================
-- Per-service databases (each owned by its user)
-- =======================================================
CREATE DATABASE litellm  OWNER litellm;
CREATE DATABASE flowisedb OWNER flowise;
CREATE DATABASE langfuse  OWNER langfuse;
CREATE DATABASE agentdb   OWNER agentuser;

-- =======================================================
-- Revoke public connection access (defence-in-depth)
-- =======================================================
REVOKE CONNECT ON DATABASE litellm   FROM PUBLIC;
REVOKE CONNECT ON DATABASE flowisedb FROM PUBLIC;
REVOKE CONNECT ON DATABASE langfuse  FROM PUBLIC;
REVOKE CONNECT ON DATABASE agentdb   FROM PUBLIC;

-- =======================================================
-- pgvector extension (vector similarity search for RAG)
-- =======================================================
\connect agentdb
CREATE EXTENSION IF NOT EXISTS vector;
